service: bible
runtime: python38

automatic_scaling:
  max_instances: 10

handlers:
# All urls that have an extension are routed to the static folder.
# Everything else is sent to the main script 
- url: /(.*\..{2,4})$
  static_files: static/\1
  upload: static/.*
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto